### PR TITLE
Changed: allow custom reporter to use emmiter

### PR DESCRIPTION
**Pull request by MoOx**
`this.emitError` or `this.emitWarning` should be available

Idea grabbed from jshint-loader

### CODE REVIEW

**Comment by unindented** [comment]
Good idea.

**Comment by unindented** [comment]
Aah, now I remember why results were wrapped in an array. It's the way the default reporters expect the results to be. See for example https://github.com/jscs-dev/node-jscs/blob/b370466323d40517edc6f86cfbf4e5f4435fb2f3/lib/reporters/inline.js

I've removed your second commit, so you will have access to `this` from the reporter, but the results will still be an array, for compatibility.

I've published v0.0.3 (https://www.npmjs.com/package/jscs-loader). Let me know if it works for you.

**Comment by MoOx** [comment]
The way loaders work in webpack shoud not make us able to use jscs reporters.
See jshint-loader note https://github.com/webpack/jshint-loader#custom-reporter

**Comment by unindented** [comment]
You are right, default reporters are not going to be of much use. I'm going to reapply your change, update the docs, and change the example.

**Comment by unindented** [comment]
@MoOx I've published v0.0.4 with results not wrapped in an array, and I've updated the docs and the example.

**Pull request merged**
